---
default_language_version:
  python: "python3.11"
exclude: "^.*\b(migrations)\b.*$"
repos:
  - repo: "https://github.com/adamchainz/django-upgrade"
    rev: "1.30.0"
    hooks:
      - id: "django-upgrade"
        args: ['--target-version', '5.1']
  - repo: "https://github.com/astral-sh/ruff-pre-commit"
    rev: "v0.15.4"
    hooks:
      - id: "ruff"
        args: ["--fix"]
      - id: "ruff-format"
  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: 'v1.19.1'
    hooks:
      - id: "mypy"
        exclude: "src/.*/migrations/.*.py"
        additional_dependencies:
          - "django-stubs[compatible-mypy]"
          - "types-requests"
          - "demoji==1.1.0"
          - "django-allauth[socialaccount]==65.14.3"
          - "django-bootstrap5==25.1"
          - "django-cleanup==9.0.0"
          - "django-cors-headers==4.7.0"
          - "django-debug-toolbar==5.2.0"
          - "django-filter==25.1"
          - "django-guardian==2.4.0"
          - "django-htmx==1.23.0"
          - "django-ninja==1.4.3"
          - "django-oauth-toolkit==3.2.0"
          - "django-polymorphic==4.11.0"
          - "django-stubs-ext==5.2.9"
          - "django-tables2==2.8.0"
          - "django-taggit==6.1.0"
          - "environs[django]==14.2.0"
          - "fontawesomefree==6.6.0"
          - "orjson==3.10.18"
          - "psycopg2-binary==2.9.10"
          - "shortuuid==1.0.13"
...
