# Generated by Django 4.1.1 on 2022-09-24 21:17

from django.db import migrations, models
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="original",
            field=models.FileField(
                help_text="The original uploaded video file.",
                max_length=255,
                upload_to=videos.models.get_video_upload_path,
            ),
        ),
    ]
