# Generated by Django 5.2.11 on 2026-06-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_original'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
    ]
