# Generated by Django 5.1.3 on 2024-12-03 13:49

import utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageversion',
            name='job',
            field=models.OneToOneField(help_text='The Job which triggered uploading of this image version.', on_delete=utils.models.NP_CASCADE, to='jobs.imageconversionjob'),
        ),
        migrations.AddConstraint(
            model_name='imageversion',
            constraint=models.UniqueConstraint(fields=('image', 'width', 'height', 'mimetype'), name='unique_image_version'),
        ),
    ]
