# Generated by Django 5.1.3 on 2024-11-18 20:39

import utils.models
import utils.upload
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='original',
            field=utils.models.NoPillowPictureField(aspect_ratios=[None], breakpoints={'lg': 992, 'md': 768, 'sm': 576, 'xl': 1200, 'xs': 0, 'xxl': 1400}, container_width=4000, file_types=['WEBP'], grid_columns=12, height_field='height', help_text='The original uploaded image.', max_length=255, pixel_densities=[1, 2], upload_to=utils.upload.get_upload_path, width_field='width'),
        ),
    ]
