# Generated by Django 5.1.4 on 2024-12-08 07:37

import utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_initial'),
        ('images', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageversion',
            name='image',
            field=models.ForeignKey(help_text='The Image this is a smaller version of.', on_delete=utils.models.NP_CASCADE, related_name='image_versions', to='files.basefile'),
        ),
    ]
