# Generated by Django 5.1.4 on 2025-01-03 22:27

import pictures.models
import utils.storage
import utils.upload
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='original',
            field=pictures.models.PictureField(aspect_ratios=[None], breakpoints={'lg': 992, 'md': 768, 'sm': 576, 'xl': 1200, 'xs': 0, 'xxl': 1400}, container_width=4000, file_types=['WEBP'], grid_columns=12, height_field='height', help_text='The original uploaded image.', max_length=255, pixel_densities=[1, 2], storage=utils.storage.BmaFileSystemStorage, upload_to=utils.upload.get_upload_path, width_field='width'),
        ),
        migrations.AlterField(
            model_name='imageversion',
            name='imagefile',
            field=pictures.models.PictureField(aspect_ratios=[None], breakpoints={'lg': 992, 'md': 768, 'sm': 576, 'xl': 1200, 'xs': 0, 'xxl': 1400}, container_width=4000, file_types=['WEBP'], grid_columns=12, height_field='height', help_text='The image version file.', max_length=255, pixel_densities=[1, 2], storage=utils.storage.BmaFileSystemStorage, upload_to=utils.upload.get_image_version_path, width_field='width'),
        ),
    ]
