# Generated by Django 5.1.7 on 2025-05-01 06:09

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_image_original_alter_imageversion_imagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='aspect_ratio',
            field=models.CharField(help_text="The aspect ratio (width/height) of the image expressed as a string like '16/9'.", max_length=20, validators=[utils.validators.validate_ratio]),
        ),
        migrations.AlterField(
            model_name='imageversion',
            name='aspect_ratio',
            field=models.CharField(help_text="The intended (and advertised) aspect ratio of this image, expressed as a string like '16/9'. The actual image AR (width/height) can vary slightly from the value in this field because of rounding errors when resizing images.", max_length=20, validators=[utils.validators.validate_ratio]),
        ),
    ]
