# Generated by Django 5.2.11 on 2026-06-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_image_crop_center_x_image_crop_center_y'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
    ]
