# Generated by Django 5.1.7 on 2025-05-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='Unnamed user', help_text='The display name for this user.', max_length=100),
        ),
    ]
