# Generated by Django 3.2.12 on 2022-05-30 05:13

import audios.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Moderation'), ('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished'), ('DELETED', 'Deleted')], help_text='The status of this file. Only published files are visible on the website.', max_length=20)),
                ('original_filename', models.CharField(help_text='The original (uploaded) filename.', max_length=255)),
                ('audio', models.FileField(upload_to=audios.models.get_audio_upload_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
