# Generated by Django 5.2.11 on 2026-06-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0002_alter_audio_original'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={},
        ),
    ]
