# Generated by Django 5.1.3 on 2024-11-15 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taggedfile',
            name='tagger',
            field=models.ForeignKey(help_text='The user who did the tagging.', on_delete=django.db.models.deletion.CASCADE, related_name='taggings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='taggedfile',
            constraint=models.UniqueConstraint(fields=('tagger', 'tag', 'content_object'), name='unique_user_tag'),
        ),
    ]
