# Generated by Django 4.1.1 on 2022-10-09 18:45

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("utils", "0001_initial"),
        ("taggit", "0005_auto_20220424_2025"),
        ("pictures", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="The tags for this picture",
                through="utils.UUIDTaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
