# Generated by Django 3.2.12 on 2022-06-03 20:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='The name of this gallery. Keep it under 100 characters please.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='The description of this gallery. Optional.')),
                ('slug', models.SlugField(blank=True, help_text='The URL slug for this gallery. Leave blank to generate based on name.')),
                ('license', models.CharField(choices=[('cc-zero-1.0', 'Creative Commons CC0 1.0 Universal'), ('cc-by-4.0', 'Creative Commons Attribution 4.0 International'), ('cc-by-sa-4.0', 'Creative Commons Attribution-ShareAlike 4.0 International')], help_text='The license for files in this gallery.', max_length=20)),
                ('attribution', models.CharField(help_text='The attribution text for files in this gallery. This is usually the real name of the creator/copyright holder.', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Moderation'), ('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished'), ('DELETED', 'Deleted')], default='PENDING', help_text='The status of this gallery. Only published galleries are visible on the website.', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryFile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Moderation'), ('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished'), ('DELETED', 'Deleted')], help_text='The status of this file. Only published files are visible on the website.', max_length=20)),
                ('original_filename', models.CharField(help_text='The original (uploaded) filename.', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
