# Generated by Django 3.2.12 on 2022-05-22 18:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='The name of this gallery. Keep it under 100 characters please.', max_length=100)),
                ('slug', models.SlugField(help_text='The URL slug for this gallery. Leave blank to generate based on name.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
