# Generated by Django 3.2.12 on 2022-05-30 05:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='The name of this gallery. Keep it under 100 characters please.', max_length=100)),
                ('slug', models.SlugField(help_text='The URL slug for this gallery. Leave blank to generate based on name.')),
                ('license', models.CharField(choices=[('cc-zero-1.0', 'Creative Commons CC0 1.0 Universal'), ('cc-by-4.0', 'Creative Commons Attribution 4.0 International'), ('cc-by-sa-4.0', 'Creative Commons Attribution-ShareAlike 4.0 International')], help_text='The license for files in this gallery.', max_length=20)),
                ('attribution', models.CharField(help_text='The attribution text for files in this gallery. This is usually the real name of the creator/copyright holder.', max_length=255)),
                ('published', models.BooleanField(default=True, help_text='Is the gallery published on the website or not.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
