# Generated by Django 3.2.12 on 2022-05-28 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='owner',
            field=models.ForeignKey(help_text='The photographer / copyright holder for this file.', on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_gallery', to=settings.AUTH_USER_MODEL),
        ),
    ]
