# Generated by Django 3.2.12 on 2022-05-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_gallery_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='license',
            field=models.CharField(choices=[('cc-zero-1.0', 'Creative Commons CC0 1.0 Universal'), ('cc-by-4.0', 'Creative Commons Attribution 4.0 International'), ('cc-by-sa-4.0', 'Attribution-ShareAlike 4.0 International')], help_text='The license for files in this gallery.', max_length=20, null=True),
        ),
    ]
