# Generated by Django 4.1.1 on 2022-09-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galleries", "0005_alter_galleryfile_gallery_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryfile",
            name="source",
            field=models.URLField(
                blank=True,
                help_text="The URL to the original source of this work. Leave blank to consider the BMA URL the original source.",
            ),
        ),
    ]
