# Generated by Django 3.2.12 on 2022-05-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0005_alter_gallery_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='attribution',
            field=models.CharField(default='Unknown', help_text='The attribution text for files in this gallery. This is usually the real name of the creator/copyright holder.', max_length=255),
            preserve_default=False,
        ),
    ]
