# Generated by Django 3.2.12 on 2022-05-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0006_gallery_attribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='published',
            field=models.BooleanField(default=True, help_text='Is the gallery published on the website or not.'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='license',
            field=models.CharField(choices=[('cc-zero-1.0', 'Creative Commons CC0 1.0 Universal'), ('cc-by-4.0', 'Creative Commons Attribution 4.0 International'), ('cc-by-sa-4.0', 'Creative Commons Attribution-ShareAlike 4.0 International')], help_text='The license for files in this gallery.', max_length=20),
        ),
    ]
