# Generated by Django 3.2.12 on 2022-08-28 10:44

from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('galleryfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='galleries.galleryfile')),
                ('original', models.FileField(help_text='The original uploaded file.', upload_to=documents.models.get_document_upload_path)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('galleries.galleryfile',),
        ),
    ]
