# Generated by Django 5.1.4 on 2025-01-03 22:27

import utils.storage
import utils.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='original',
            field=models.FileField(help_text='The original uploaded document file.', max_length=255, storage=utils.storage.BmaFileSystemStorage, upload_to=utils.upload.get_upload_path),
        ),
    ]
