# Generated by Django 4.1.1 on 2022-09-24 21:17

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_document_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="original",
            field=models.FileField(
                help_text="The original uploaded file.",
                max_length=255,
                upload_to=documents.models.get_document_upload_path,
            ),
        ),
    ]
