# Generated by Django 3.2.12 on 2022-05-28 14:52

from django.db import migrations, models
import django.db.models.deletion
import photos.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Moderation'), ('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished'), ('DELETED', 'Deleted')], help_text='The status of this file. Only published files are visible on the website.', max_length=20)),
                ('original_filename', models.CharField(help_text='The original (uploaded) filename.', max_length=255)),
                ('photo', models.ImageField(upload_to=photos.models.get_photo_upload_path)),
                ('gallery', models.ForeignKey(help_text='The gallery this file belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='galleries.gallery')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
