# Generated by Django 3.2.12 on 2022-06-03 20:07

from django.db import migrations, models
import django.db.models.deletion
import photos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('galleryfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='galleries.galleryfile')),
                ('original', models.ImageField(help_text='The original uploaded file.', upload_to=photos.models.get_photo_upload_path)),
                ('gallery', models.ForeignKey(help_text='The gallery this photo belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='galleries.gallery')),
            ],
            options={
                'abstract': False,
            },
            bases=('galleries.galleryfile',),
        ),
    ]
