# Generated by Django 3.2.12 on 2022-05-22 18:29

from django.db import migrations, models
import django.db.models.deletion
import photos.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(help_text='The original (uploaded) filename.', max_length=255)),
                ('photo', models.ImageField(upload_to=photos.models.get_photo_upload_path)),
                ('gallery', models.ForeignKey(help_text='The gallery this file belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='gallery_photos', to='galleries.gallery')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
