# Generated by Django 3.2.12 on 2022-05-27 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_gallery_tags'),
        ('photos', '0002_photo_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='gallery',
            field=models.ForeignKey(help_text='The gallery this file belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='galleries.gallery'),
        ),
    ]
