# Generated by Django 3.2.12 on 2022-05-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_gallery_delete_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Moderation'), ('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished'), ('DELETED', 'Deleted')], default='PENDING', help_text='The status of this file. Only published files are visible on the website.', max_length=20),
            preserve_default=False,
        ),
    ]
