# Generated by Django 5.1.2 on 2024-11-03 16:47

import django.db.models.deletion
import files.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileGroupObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileUserObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaseFile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique ID (UUID4) of this object.', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time when this object was first created.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The date and time when this object was last updated.')),
                ('title', models.CharField(help_text='The title of this work. Required. Defaults to the original uploaded filename.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='The description of this work. Optional. Supports markdown.')),
                ('original_source', models.URLField(blank=True, help_text='The URL to the original source of this work. Leave blank to consider the BMA URL the original source.')),
                ('license', models.CharField(choices=[('CC_ZERO_1_0', 'Creative Commons CC0 1.0 Universal'), ('CC_BY_4_0', 'Creative Commons Attribution 4.0 International'), ('CC_BY_SA_4_0', 'Creative Commons Attribution-ShareAlike 4.0 International')], help_text='The license for this file. The license can not be changed after the file(s) is uploaded.', max_length=255)),
                ('attribution', models.CharField(help_text='The attribution text for this file. This is usually the real name or handle of the author(s) or licensor of the file.', max_length=255)),
                ('approved', models.BooleanField(default=False, help_text='Has this file been approved by a moderator?')),
                ('published', models.BooleanField(default=False, help_text='Has this file been published?')),
                ('deleted', models.BooleanField(default=False, help_text='Has this file been deleted?')),
                ('original_filename', models.CharField(help_text='The original (uploaded) filename. This value is read-only.', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='The size of the file in bytes. This value is read-only.')),
                ('thumbnail_url', models.CharField(help_text='Relative URL to the image to use as thumbnail for this file. This must be a string beginning with /static/images/ or /media/', max_length=255, validators=[files.validators.validate_thumbnail_url])),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
                'ordering': ('created',),
                'permissions': (('unapprove_basefile', 'Unapprove file'), ('approve_basefile', 'Approve file'), ('unpublish_basefile', 'Unpublish file'), ('publish_basefile', 'Publish file'), ('undelete_basefile', 'Undelete file'), ('softdelete_basefile', 'Soft delete file')),
            },
        ),
    ]
