# Generated by Django 4.1.2 on 2022-10-16 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.sentinel


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="basefile",
            name="owner",
            field=models.ForeignKey(
                help_text="The uploader of this file.",
                on_delete=models.SET(users.sentinel.get_sentinel_user),
                related_name="files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="basefile",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
