# Generated by Django 4.1.1 on 2022-10-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basefile",
            name="file_size",
            field=models.PositiveIntegerField(
                blank=True, help_text="The size of the file.", null=True
            ),
        ),
    ]
