# Generated by Django 4.1.1 on 2022-10-01 16:19

from django.conf import settings
from django.db import migrations, models
import users.sentinel


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("files", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basefile",
            name="owner",
            field=models.ForeignKey(
                help_text="The uploader of this file.",
                on_delete=models.SET(users.sentinel.get_sentinel_user),
                related_name="files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
