# Generated by Django 4.1.2 on 2022-10-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basefile",
            name="source",
            field=models.URLField(
                blank=True,
                help_text="The URL to the original source of this work. Leave blank to consider the BMA URL the original source.",
            ),
        ),
    ]
