# Generated by Django 5.1.3 on 2024-12-03 13:49

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0002_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basefile',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='The tags for this file', through='tags.TaggedFile', to='tags.BmaTag', verbose_name='Tags'),
        ),
    ]
