# Generated by Django 4.1.1 on 2022-10-08 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_alter_basefile_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basefile",
            options={
                "ordering": ["created"],
                "permissions": (
                    ("approve_basefile", "Approve file"),
                    ("unpublish_basefile", "Unpublish file"),
                    ("publish_basefile", "Publish file"),
                ),
            },
        ),
    ]
