# Generated by Django 5.1.3 on 2024-11-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basefile',
            name='file_size',
            field=models.BigIntegerField(help_text='The size of the file in bytes. This value is read-only.'),
        ),
    ]
