# Generated by Django 5.1.4 on 2025-01-03 22:27

import pictures.models
import utils.storage
import utils.upload
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='imagefile',
            field=pictures.models.PictureField(aspect_ratios=[None], breakpoints={'lg': 992, 'md': 768, 'sm': 576, 'xl': 1200, 'xs': 0, 'xxl': 1400}, container_width=4000, file_types=['WEBP'], grid_columns=12, height_field='height', help_text='The thumbnail file.', max_length=255, pixel_densities=[1, 2], storage=utils.storage.BmaFileSystemStorage, upload_to=utils.upload.get_thumbnail_path, width_field='width'),
        ),
        migrations.AlterField(
            model_name='thumbnailsource',
            name='source',
            field=pictures.models.PictureField(aspect_ratios=['1/1', '4/3', '16/9', '2/3'], breakpoints={'lg': 992, 'md': 768, 'sm': 576, 'xl': 1200, 'xs': 0, 'xxl': 1400}, container_width=200, file_types=['WEBP'], grid_columns=4, height_field='height', help_text='The source image from which all the thumbnails are created.', max_length=255, pixel_densities=[1, 2], storage=utils.storage.BmaFileSystemStorage, upload_to=utils.upload.get_thumbnail_source_path, width_field='width'),
        ),
    ]
