# Generated by Django 4.1.1 on 2022-10-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="albummember",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The date and time when this file was first added to the album.",
            ),
        ),
    ]
