# Generated by Django 4.1.2 on 2022-10-16 15:18

from django.conf import settings
from django.db import migrations, models
import users.sentinel


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("albums", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="owner",
            field=models.ForeignKey(
                help_text="The creator of this album.",
                on_delete=models.SET(users.sentinel.get_sentinel_user),
                related_name="albums",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
