# Generated by Django 5.1.3 on 2024-11-15 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='basejob',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who is handling the job.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ThumbnailJob',
            fields=[
                ('imageconversionjob_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jobs.imageconversionjob')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('jobs.imageconversionjob',),
        ),
    ]
