# Generated by Django 5.1.2 on 2024-11-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basejob',
            name='useragent',
            field=models.CharField(blank=True, default='', help_text='Text description of the client handling this job.', max_length=255),
        ),
        migrations.AlterField(
            model_name='imageconversionjob',
            name='aspect_ratio_denominator',
            field=models.PositiveIntegerField(blank=True, help_text='The denominator part of the desired aspect ratio of the image. Leave blank to keep original AR.', null=True),
        ),
        migrations.AlterField(
            model_name='imageconversionjob',
            name='aspect_ratio_numerator',
            field=models.PositiveIntegerField(blank=True, help_text='The numerator part of the desired aspect ratio of the image. Leave blank to keep original AR.', null=True),
        ),
    ]
