# Generated by Django 5.1.7 on 2025-05-01 06:09

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageconversionjob',
            name='custom_aspect_ratio',
            field=models.CharField(blank=True, help_text='Specifies the desired aspect ratio of the converted image. Blank if the AR of the source image is to be maintained. Used by the converting client to decide on resize method (crop or maintain ratio) and by the server to create the ImageVersion/Thumbnail object correctly when the result is uploaded.', max_length=20, validators=[utils.validators.validate_ratio]),
        ),
        migrations.AlterField(
            model_name='thumbnailjob',
            name='custom_aspect_ratio',
            field=models.CharField(blank=True, help_text='Specifies the desired aspect ratio of the converted image. Blank if the AR of the source image is to be maintained. Used by the converting client to decide on resize method (crop or maintain ratio) and by the server to create the ImageVersion/Thumbnail object correctly when the result is uploaded.', max_length=20, validators=[utils.validators.validate_ratio]),
        ),
    ]
