# Generated by Django 5.1.7 on 2025-05-04 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_imageconversionjob_custom_aspect_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageconversionjob',
            name='crop_center_x',
            field=models.PositiveSmallIntegerField(default=50, help_text='The crop center point on the X axis expressed as an integer between 0 and 100, where 0 is at the left edge of the image, and 100 is on the right edge. Default: 50', validators=[django.core.validators.MaxValueValidator(limit_value=100)]),
        ),
        migrations.AddField(
            model_name='imageconversionjob',
            name='crop_center_y',
            field=models.PositiveSmallIntegerField(default=50, help_text='The crop center point on the Y axis expressed as an integer between 0 and 100, where 0 is at the left edge of the image, and 100 is on the right edge. Default: 50', validators=[django.core.validators.MaxValueValidator(limit_value=100)]),
        ),
        migrations.AddField(
            model_name='thumbnailjob',
            name='crop_center_x',
            field=models.PositiveSmallIntegerField(default=50, help_text='The crop center point on the X axis expressed as an integer between 0 and 100, where 0 is at the left edge of the image, and 100 is on the right edge. Default: 50', validators=[django.core.validators.MaxValueValidator(limit_value=100)]),
        ),
        migrations.AddField(
            model_name='thumbnailjob',
            name='crop_center_y',
            field=models.PositiveSmallIntegerField(default=50, help_text='The crop center point on the Y axis expressed as an integer between 0 and 100, where 0 is at the left edge of the image, and 100 is on the right edge. Default: 50', validators=[django.core.validators.MaxValueValidator(limit_value=100)]),
        ),
    ]
