# Generated by Django 5.1.2 on 2024-11-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_basejob_useragent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageconversionjob',
            name='aspect_ratio_denominator',
        ),
        migrations.RemoveField(
            model_name='imageconversionjob',
            name='aspect_ratio_numerator',
        ),
        migrations.AddField(
            model_name='imageconversionjob',
            name='height',
            field=models.PositiveIntegerField(default=100, help_text='The desired height of the converted image.'),
            preserve_default=False,
        ),
    ]
