# Generated by Django 5.1.2 on 2024-11-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_imageconversionjob_aspect_ratio_denominator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageconversionjob',
            name='custom_aspect_ratio',
            field=models.BooleanField(default=False, help_text='True if this job needs cropping to a custom AR, False if no crop is needed.'),
        ),
    ]
