# Generated by Django 5.2.11 on 2026-06-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_imageconversionjob_crop_center_x_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basejob',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fileuploadjob',
            options={},
        ),
        migrations.AlterModelOptions(
            name='imageexifextractionjob',
            options={},
        ),
        migrations.AlterModelOptions(
            name='thumbnailsourcejob',
            options={},
        ),
    ]
