# Generated by Django 5.1.3 on 2024-11-10 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_imageconversionjob_custom_aspect_ratio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basejob',
            old_name='useragent',
            new_name='client_version',
        ),
    ]
